FEATURE_COLUMNS = [
    "Destination Port",
    "Protocol",
    "Flow Duration",
    "Bwd Packet Length Max",
    "Bwd Packet Length Min",
    "Bwd Packet Length Mean",
    "Bwd Packet Length Std",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Flow IAT Max",
    "Fwd IAT Total",
    "Fwd IAT Mean",
    "Fwd IAT Std",
    "Fwd IAT Max",
    "Bwd IAT Std",
    "Bwd IAT Max",
    "Min Packet Length",
    "Max Packet Length",
    "Packet Length Mean",
    "Packet Length Std",
    "Packet Length Variance",
    "FIN Flag Count",
    "PSH Flag Count",
    "ACK Flag Count",
    "Down/Up Ratio",
    "Average Packet Size",
    "Avg Bwd Segment Size",
    "Init_Win_bytes_forward",
    "Idle Mean",
    "Idle Std",
    "Idle Max",
    "Idle Min",
]

COLUMN_ALIASES = {
    "Destination_Port": "Destination Port",
    "Flow_Duration": "Flow Duration",
    "Bwd_Packet_Length_Max": "Bwd Packet Length Max",
    "Bwd_Packet_Length_Min": "Bwd Packet Length Min",
    "Bwd_Packet_Length_Mean": "Bwd Packet Length Mean",
    "Bwd_Packet_Length_Std": "Bwd Packet Length Std",
    "Flow_IAT_Mean": "Flow IAT Mean",
    "Flow_IAT_Std": "Flow IAT Std",
    "Flow_IAT_Max": "Flow IAT Max",
    "Fwd_IAT_Total": "Fwd IAT Total",
    "Fwd_IAT_Mean": "Fwd IAT Mean",
    "Fwd_IAT_Std": "Fwd IAT Std",
    "Fwd_IAT_Max": "Fwd IAT Max",
    "Bwd_IAT_Std": "Bwd IAT Std",
    "Bwd_IAT_Max": "Bwd IAT Max",
    "Min_Packet_Length": "Min Packet Length",
    "Max_Packet_Length": "Max Packet Length",
    "Packet_Length_Mean": "Packet Length Mean",
    "Packet_Length_Std": "Packet Length Std",
    "Packet_Length_Variance": "Packet Length Variance",
    "FIN_Flag_Count": "FIN Flag Count",
    "PSH_Flag_Count": "PSH Flag Count",
    "ACK_Flag_Count": "ACK Flag Count",
    "Down/Up_Ratio": "Down/Up Ratio",
    "Average_Packet_Size": "Average Packet Size",
    "Avg_Bwd_Segment_Size": "Avg Bwd Segment Size",
    "Idle_Mean": "Idle Mean",
    "Idle_Std": "Idle Std",
    "Idle_Max": "Idle Max",
    "Idle_Min": "Idle Min",
}